[[connections]]
title = "The Gao Log"
description = "Gather and Observe"
link = "https://wensimehrp.github.io"

[[connections]]
title = "Uwni'Space"
description = "The stray crows fly and flutter in the sky, Together they depart, together they return."
link = "https://uwni.blog"
