// This thing is compiled anyways
#let trips = (
  (
    date: datetime(year: 2024, month: 08, day: 30),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 UBC",
    departure: "W 41 Ave @ Granville St",
    arrival: "SW Marine Dr",
    fare: "CA$2.15",
    notes: "Concession fare; mechanical failure",
  ),
  (
    date: datetime(year: 2024, month: 08, day: 30),
    agency: "TransLink",
    type: "Bus",
    route: "49 UBC",
    departure: "SW Marine Dr",
    arrival: "Wesbrook Mall @ Birney Ave",
    notes: "Picked up passenger from failed bus",
  ),
  (
    date: datetime(year: 2024, month: 08, day: 30),
    agency: "TransLink",
    type: "Bus",
    route: "25 Brentwood",
    departure: "W 16 Ave @ Wesbrook Mall",
    arrival: "Dunbar St @ W 17 Ave",
  ),
  (
    date: datetime(year: 2024, month: 08, day: 30),
    agency: "TransLink",
    type: "Bus",
    route: "7 Dunbar",
    departure: "Dunbar St @ W 17 Ave",
    arrival: "Dunbar St @ W 39 Ave",
  ),
  (
    date: datetime(year: 2024, month: 12, day: 24),
    agency: "TransLink",
    type: "Bus",
    route: "17 Oak",
    departure: "Oak St @ W 33 Ave",
    arrival: "Marine Drive Station",
  ),
  (
    date: datetime(year: 2024, month: 12, day: 24),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "Marine Drive Station",
    arrival: "Aberdeen Station",
    fare: "CA$3.20",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2024, month: 12, day: 24),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "Aberdeen Station",
    arrival: "Oakridge–41st Ave Station",
    fare: "CA$3.20",
    notes: "Concession fare",
  ),
  (
    dateStr: "Early 2025",
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "Oakridge–41st Ave Station",
    arrival: "Bridgeport Station",
    fare: "CA$3.20",
    notes: "Concession fare",
  ),
  (
    dateStr: "Early 2025",
    agency: "TransLink",
    type: "Bus",
    route: "620 Tsawwassen",
    departure: "Bridgeport Station",
    arrival: "Tsawwassen Ferry Terminal",
  ),
  (
    dateStr: "Early 2025",
    agency: "BC Ferries",
    type: "Ferry",
    route: "Van-Victoria",
    vehicle: "Coastal Celebration",
    departure: "Tsawwassen Ferry Terminal",
    arrival: "Swartz Bay Terminal",
    fare: "CA$15.00",
  ),
  (
    dateStr: "Early 2025",
    agency: "BC Ferries",
    type: "Ferry",
    route: "Victoria-Van",
    vehicle: "Spirit of British Columbia",
    departure: "Swartz Bay Terminal",
    arrival: "Tsawwassen Ferry Terminal",
    fare: "CA$15.00",
  ),
  (
    dateStr: "Mid 2025",
    agency: "Cathay Pacific",
    type: "Plane",
    route: "CX 865",
    departure: "YVR (CYVR)",
    arrival: "HKG (VHHH)",
  ),
  (
    dateStr: "Mid 2025",
    agency: "Cathay Pacific",
    type: "Plane",
    route: "CX 316",
    departure: "HKG (VHHH)",
    arrival: "PVG (ZSPD)",
  ),
  (
    dateStr: "Mid 2025",
    agency: "Cathay Pacific",
    type: "Plane",
    route: "CX 381",
    departure: "PVG (ZSPD)",
    arrival: "HKG (VHHH)",
  ),
  (
    dateStr: "Mid 2025",
    agency: "Cathay Pacific",
    type: "Plane",
    route: "CX 888",
    departure: "HKG (VHHH)",
    arrival: "YVR (CYVR)",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 16),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 UBC",
    departure: "W 41 Ave @ Granville St",
    arrival: "W 16 Ave @ Wesbrook Mall",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 16),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 Joyce",
    departure: "W 16 Ave @ Wesbrook Mall",
    arrival: "W 41 Ave @ Granville St",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 17),
    agency: "TransLink",
    type: "Bus",
    route: "25 UBC",
    departure: "W King Edward Ave @ Granville St",
    arrival: "W 16 Ave @ Wallace St",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 17),
    agency: "TransLink",
    type: "Bus",
    route: "25 UBC",
    departure: "W 16 Ave @ Camosun St",
    arrival: "Wesbrook Mall @ 2100 Block",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 17),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 Joyce",
    departure: "UBC Exchange",
    arrival: "W 41 Ave @ Granville St",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 28),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Expo Line",
    departure: "Commercial–Broadway station",
    arrival: "Metrotown Station",
    fare: "CA$3.30",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 28),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Expo Line",
    departure: "Metrotown Station",
    arrival: "Joyce–Collingwood Station",
    fare: "CA$3.30",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 28),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 UBC",
    departure: "Joyce Station",
    arrival: "W 41 Ave @ Granville St",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 30),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 Joyce",
    departure: "W 41 Ave @ Granville St",
    arrival: "Joyce Station",
    fare: "CA$3.30",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 30),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Expo Line",
    departure: "Joyce–Collingwood Station",
    arrival: "Metrotown Station",
    fare: 0.00,
  ),
  (
    date: datetime(year: 2025, month: 08, day: 30),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Expo Line",
    departure: "Metrotown Station",
    arrival: "Waterfront Station",
    fare: "CA$3.30",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 08, day: 30),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "Waterfront Station",
    arrival: "Oakridge–41st Ave Station",
    fare: 0.00,
  ),
  (
    date: datetime(year: 2025, month: 09, day: 01),
    agency: "TransLink",
    type: "Bus",
    route: "17 Oak",
    departure: "Oak St @ W 33 Ave",
    arrival: "Marine Drive Station",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 01),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "Marine Drive Station",
    arrival: "Aberdeen Station",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 05),
    agency: "TransLink",
    type: "Bus",
    route: "17 Oak",
    departure: "Oak St @ W 33 Ave",
    arrival: "Oak St @ W 49 Ave",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 05),
    agency: "TransLink",
    type: "Bus",
    route: "49 Metrotown",
    departure: "W 49 Ave @ Oak St",
    arrival: "Metrotown Station",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 05),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Expo Line",
    departure: "Metrotown Station",
    arrival: "Joyce–Collingwood Station",
    fare: "CA$3.30",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 05),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 UBC",
    departure: "Joyce Station",
    arrival: "W 41 Ave @ Granville St",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 06),
    agency: "TransLink",
    type: "Bus",
    route: "17 Oak",
    departure: "Oak St @ Devonshire Cres",
    arrival: "Oak St @ W 41st Ave",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 06),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 UBC",
    departure: "W 41 Ave @ Oak St",
    arrival: "W 16 Ave @ Wesbrook Mall",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 06),
    agency: "TransLink",
    type: "B-Line",
    route: "99 Commercial-Broadway B-Line",
    departure: "UBC Exchange",
    arrival: "Broadway-City Hall Station",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 06),
    agency: "TransLink",
    type: "Bus",
    route: "17 Oak",
    departure: "Broadway-City Hall Station",
    arrival: "Oak St @ Devonshire Cres",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 08),
    agency: "TransLink",
    type: "Bus",
    route: "17 Downtown",
    departure: "Oak St @ Devonshire Cres",
    arrival: "Robson & Hamilton",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 08),
    agency: "TransLink",
    type: "Bus",
    route: "17 Oak",
    departure: "Robson & Hamilton",
    arrival: "Granville St @ W Pender St",
    notes: "Non-stop",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 08),
    agency: "TransLink",
    type: "RapidBus",
    route: "R5 SFU",
    departure: "Hastings St @ Granville St",
    arrival: "Hastings St @ Renfrew St",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 08),
    agency: "TransLink",
    type: "Bus",
    route: "27 Joyce",
    departure: "Adanac St @ Skeena St",
    arrival: "Joyce Station",
    fare: "CA$2.25",
    notes: "Concession fare",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 08),
    agency: "TransLink",
    type: "RapidBus",
    route: "R4 UBC",
    departure: "Joyce Station",
    arrival: "W 41 Ave @ Granville St",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 20),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "King Edward Station",
    arrival: "Aberdeen Station",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 20),
    agency: "TransLink",
    type: "SkyTrain",
    route: "Canada Line",
    departure: "Aberdeen Station",
    arrival: "Oakridge–41st Ave Station",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 28),
    agency: "TransLink",
    route: "49 UBC",
    departure: "Metrotown Station",
    arrival: "W 49 Ave @ Oak St",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 28),
    agency: "TransLink",
    route: "17 Downtown",
    departure: "Oak St @ W 49 Ave",
    arrival: "Oak St @ W 33 Ave",
  ),
  (
    date: datetime(year: 2025, month: 09, day: 30),
    agency: "TransLink",
    route: "17 Oak",
    departure: "Oak St @ W 33 Ave",
    arrival: "Oak St @ W 41 Ave",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 9, day: 30),
    agency: "TransLink",
    route: "R4 UBC",
    departure: "W 41 Ave @ Oak St",
    arrival: "UBC Exchange",
    vehicle: "B19011",
  ),
  (
    date: datetime(year: 2025, month: 9, day: 30),
    agency: "TransLink",
    route: "R4 Joyce",
    departure: "UBC Exchange",
    arrival: "W 41 Ave @ Oak St",
    vehicle: "H18020",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 9, day: 30),
    agency: "TransLink",
    route: "17 Downtown",
    departure: "Oak St @ W 41 Ave",
    arrival: "Oak St @ W 33 Ave",
  ),
  (
    date: datetime(year: 2025, month: 10, day: 21),
    agency: "TransLink",
    route: "15 Olympic Village",
    departure: "Cambie St @ W 33 Ave",
    arrival: "Olympic Village Station",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 10, day: 21),
    agency: "TransLink",
    route: "50 Waterfront",
    departure: "Olympic Village Station",
    arrival: "W 2nd Ave @ Anderson St",
    notes: "Cont'd from previous trip",
  ),
  (
    date: datetime(year: 2025, month: 10, day: 21),
    agency: "TransLink",
    route: "50 False Creek / Granville Island",
    departure: "W 2nd Ave @ Anderson St",
    arrival: "Olympic Village Station",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 10, day: 21),
    agency: "TransLink",
    route: "15 Cambie",
    departure: "Olympic Village Station",
    arrival: "Cambie St @ W 33 Ave",
    notes: "Cont'd from previous trip"
  ),
  (
    date: datetime(year: 2025, month: 10, day: 23),
    agency: "TransLink",
    route: "Canada Line",
    departure: "King Edward Station",
    arrival: "Waterfront Station",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 10, day: 23),
    agency: "TransLink",
    route: "17 Oak",
    departure: "Robson & Hamilton",
    arrival: "Oak St @ Nanton Ave",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 08),
    agency: "TransLink",
    route: "17 Downtown",
    departure: "Oak St @ Devonshire Cres",
    arrival: "Robson & Hamilton",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 08),
    agency: "TransLink",
    route: "17 Oak",
    departure: "Robson & Hamilton",
    arrival: "Granville St @ W Pender St",
    notes: "Cont'd from previous trip"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 08),
    agency: "TransLink",
    route: "SeaBus",
    departure: "Waterfront Station",
    arrival: "Lonsdale Quay Terminal",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 08),
    agency: "TransLink",
    route: "229 Lynn Valley",
    departure: "Lonsdale Quay Terminal",
    arrival: "Lonsdale Ave @ E 13 St",
    vehicle: "9767",
    notes: "Original plan was 230; bus did not come"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 12),
    agency: "TransLink",
    route: "17 Oak",
    departure: "Oak St @ Devonshire Cres",
    arrival: "Oak St @ W 41st Ave",
    fare: "CA$2.25"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 12),
    agency: "TransLink",
    route: "R4 Joyce",
    departure: "W 41 Ave @ Oak St",
    arrival: "Oakridge-41st Ave Station",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 12),
    agency: "TransLink",
    route: "Canada Line",
    departure: "Oakridge-41st Avenue",
    arrival: "Richmond–Brighouse",
    fare: "CA$1.05"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 12),
    agency: "TransLink",
    route: "Canada Line",
    departure: "Richmond–Brighouse",
    arrival: "Marine Drive Station",
    fare: "CA$2.25"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 12),
    agency: "TransLink",
    route: "17 Downtown",
    departure: "Marine Drive Station",
    arrival: "Oak St @ W 33 Ave",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 15),
    agency: "TransLink",
    route: "17 Downtown",
    departure: "Oak St @ Devonshire Cres",
    arrival: "Robson & Hamilton",
    fare: "CA$2.25",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 15),
    agency: "TransLink",
    route: "17 Oak",
    departure: "Robson & Hamilton",
    arrival: "Granville St @ W Pender St",
    notes: "Cont'd from previous trip"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 15),
    agency: "TransLink",
    route: "SeaBus",
    departure: "Waterfront Station",
    arrival: "Lonsdale Quay Terminal",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 15),
    agency: "TransLink",
    route: "229 Lynn Valley",
    departure: "Lonsdale Quay Terminal",
    arrival: "Lonsdale Ave @ E Keith Rd",
  ),
  (
    date: datetime(year: 2025, month: 11, day: 21),
    agency: "TransLink",
    route: "Canada Line",
    departure: "King Edward Station",
    arrival: "Bridgeport Station",
    fare: "CA$3.30"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 21),
    agency: "TransLink",
    route: "412 Sea Island South",
    departure: "Bridgeport Station",
    arrival: "Cowley Cres @ Inglis Dr",
    vehicle: "25501"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 21),
    agency: "TransLink",
    route: "412 Bridgeport",
    departure: "Inglis Dr @ Bell Lrving St",
    arrival: "Bridgeport Station",
    fare: "CA$2.25",
    vehicle: "25501"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 21),
    agency: "TransLink",
    route: "Canada Line",
    departure: "Bridgeport Station",
    arrival: "King Edward Station",
    fare: "CA$1.05",
    vehicle: "220"
  ),
  (
    date: datetime(year: 2025, month: 11, day: 21),
    agency: "TransLink",
    route: "33 29th Avenue",
    departure: "King Edward Station",
    arrival: "Midlothian Ave @ Clancy Loranger Way",
    vehicle: "8345"
  )
)
