[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 UBC"
departure = "W 41 Ave @ Granville St"
arrival = "SW Marine Dr"
fare = "CA$2.15"
notes = "Concession fare; mechanical failure"

[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "49 UBC"
departure = "SW Marine Dr"
arrival = "Wesbrook Mall @ Birney Ave"
notes = "Picked up passenger from failed bus"

[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "25 Brentwood"
departure = "W 16 Ave @ Wesbrook Mall"
arrival = "Dunbar St @ W 17 Ave"

[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "7 Dunbar"
departure = "Dunbar St @ W 17 Ave"
arrival = "Dunbar St @ W 39 Ave"

[[trip]]
date = 2024-12-24T00:00:00-08:00
agency = "TransLink"
type = "Bus"
route = "17 Oak"
departure = "Oak St @ W 33 Ave"
arrival = "Marine Drive Station"

[[trip]]
date = 2024-12-24T00:00:00-08:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Marine Drive Station"
arrival = "Aberdeen Station"
fare = "CA$3.20"
notes = "Concession fare"

[[trip]]
date = 2024-12-24T00:00:00-08:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Aberdeen Station"
arrival = "Oakridge–41st Ave Station"
fare = "CA$3.20"
notes = "Concession fare"

[[trip]]
dateStr = "Early 2025"
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Oakridge–41st Ave Station"
arrival = "Bridgeport Station"
fare = "CA$3.20"
notes = "Concession fare"

[[trip]]
dateStr = "Early 2025"
agency = "TransLink"
type = "Bus"
route = "620 Tsawwassen"
departure = "Bridgeport Station"
arrival = "Tsawwassen Ferry Terminal"

[[trip]]
dateStr = "Early 2025"
agency = "BC Ferries"
type = "Ferry"
route = "Van-Victoria"
vehicle = "Coastal Celebration"
departure = "Tsawwassen Ferry Terminal"
arrival = "Swartz Bay Terminal"
fare = "CA$15.00"

[[trip]]
dateStr = "Early 2025"
agency = "BC Ferries"
type = "Ferry"
route = "Victoria-Van"
vehicle = "Spirit of British Columbia"
departure = "Swartz Bay Terminal"
arrival = "Tsawwassen Ferry Terminal"
fare = "CA$15.00"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 865"
departure = "YVR (CYVR)"
arrival = "HKG (VHHH)"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 316"
departure = "HKG (VHHH)"
arrival = "PVG (ZSPD)"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 381"
departure = "PVG (ZSPD)"
arrival = "HKG (VHHH)"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 888"
departure = "HKG (VHHH)"
arrival = "YVR (CYVR)"

[[trip]]
date = 2025-08-16T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 UBC"
departure = "W 41 Ave @ Granville St"
arrival = "W 16 Ave @ Wesbrook Mall"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-16T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 Joyce"
departure = "W 16 Ave @ Wesbrook Mall"
arrival = "W 41 Ave @ Granville St"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-17T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "25 UBC"
departure = "W King Edward Ave @ Granville St"
arrival = "W 16 Ave @ Wallace St"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-17T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "25 UBC"
departure = "W 16 Ave @ Camosun St"
arrival = "Wesbrook Mall @ 2100 Block"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-17T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 Joyce"
departure = "UBC Exchange"
arrival = "W 41 Ave @ Granville St"

[[trip]]
date = 2025-08-28T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Commercial–Broadway station"
arrival = "Metrotown Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-28T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Metrotown Station"
arrival = "Joyce–Collingwood Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-28T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 UBC"
departure = "Joyce Station"
arrival = "W 41 Ave @ Granville St"

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 Joyce"
departure = "W 41 Ave @ Granville St"
arrival = "Joyce Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Joyce–Collingwood Station"
arrival = "Metrotown Station"
fare = 0.00

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Metrotown Station"
arrival = "Waterfront Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Waterfront Station"
arrival = "Oakridge–41st Ave Station"
fare = 0.00

[[trip]]
date = 2025-09-01T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "17 Oak"
departure = "Oak St @ W 33 Ave"
arrival = "Marine Drive Station"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-09-01T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Marine Drive Station"
arrival = "Aberdeen Station"

[[trip]]
date = 2025-09-05T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "17 Oak"
departure = "Oak St @ W 33 Ave"
arrival = "Oak St @ W 49 Ave"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-09-05T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "49 Metrotown"
departure = "W 49 Ave @ Oak St"
arrival = "Metrotown Station"

[[trip]]
date = 2025-09-05T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Metrotown Station"
arrival = "Joyce–Collingwood Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-09-05T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 UBC"
departure = "Joyce Station"
arrival = "W 41 Ave @ Granville St"

[[trip]]
date = 2025-09-06T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "17 Oak"
departure = "Oak St @ Devonshire Cres"
arrival = "Oak St @ W 41st Ave"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-09-06T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 UBC"
departure = "W 41 Ave @ Oak St"
arrival = "W 16 Ave @ Wesbrook Mall"

[[trip]]
date = 2025-09-06T00:00:00-07:00
agency = "TransLink"
type = "B-Line"
route = "99 Commercial-Broadway B-Line"
departure = "UBC Exchange"
arrival = "Broadway-City Hall Station"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-09-06T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "17 Oak"
departure = "Broadway-City Hall Station"
arrival = "Oak St @ Devonshire Cres"

[[trip]]
date = 2025-09-08T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "17 Downtown"
departure = "Oak St @ Devonshire Cres"
arrival = "Robson & Hamilton"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-09-08T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "17 Oak"
departure = "Robson & Hamilton"
arrival = "Granville St @ W Pender St"
notes = "Non-stop"

[[trip]]
date = 2025-09-08T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R5 SFU"
departure = "Hastings St @ Granville St"
arrival = "Hastings St @ Renfrew St"

[[trip]]
date = 2025-09-08T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "27 Joyce"
departure = "Adanac St @ Skeena St"
arrival = "Joyce Station"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-09-08T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 UBC"
departure = "Joyce Station"
arrival = "W 41 Ave @ Granville St"

[[trip]]
date = 2025-09-20T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "King Edward Station"
arrival = "Aberdeen Station"
fare = "CA$2.25"

[[trip]]
date = 2025-09-20T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Aberdeen Station"
arrival = "Oakridge–41st Ave Station"
fare = "CA$2.25"
