[[connections]]
title = "The Gao Log"
description = "Gather and Observe"
link = "https://wensimehrp.github.io"

[[connections]]
title = "Uwni'Space"
description = "<placeholder> plz complete asap"
link = "https://www.omots.io"
