[agency.TransLink]
image = "https://upload.wikimedia.org/wikipedia/commons/3/3e/TransLink_%28Vancouver%29_Logo.svg"
site = "https://translink.ca"

[agency."BC Ferries"]
image = "https://upload.wikimedia.org/wikipedia/en/2/21/BC_Ferries_Logo.svg"
site = "https://www.bcferries.com/"

[agency."Cathay Pacific"]
image = "https://upload.wikimedia.org/wikipedia/en/1/17/Cathay_Pacific_logo.svg"
site = "https://www.cathaypacific.com/"

[type.SkyTrain]
icon = "fa-solid fa-train-subway"
colorClasses = "bg-sky-100 dark:bg-sky-900 text-sky-800 dark:text-sky-200"

[type.RapidBus]
icon = "fa-solid fa-bus"
colorClasses = "bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200"

[type.Bus]
icon = "fa-solid fa-bus"
colorClasses = "bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200"

[type.Ferry]
icon = "fa-solid fa-ship"
colorClasses = "bg-blue-200 dark:bg-blue-950 text-blue-800 dark:text-blue-200"

[type.Plane]
icon = "fa-solid fa-plane"
colorClasses = "bg-indigo-100 dark:bg-indigo-900 text-indigo-800 dark:text-indigo-200"

[type.B-Line]
icon = "fa-solid fa-bus"
colorClasses = "bg-orange-100 dark:bg-orange-900 text-orange-800 dark:text-orange-200"
