[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 RapidBus"
departure = "W 41 Ave @ Granville St"
arrival = "SW Marine Dr"
fare = "CA$2.15"
notes = "Concession fare; mechanical failure"

[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "049"
departure = "SW Marine Dr"
arrival = "Wesbrook Mall @ Birney Ave"
notes = "Picked up passenger from failed bus"

[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "025"
departure = "W 16 Ave @ Wesbrook Mall"
arrival = "Southbound Dunbar St @ W 17 Ave"

[[trip]]
date = 2024-08-30T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "007"
departure = "Southbound Dunbar St @ W 17 Ave"
arrival = "Southbound Dunbar St @ W 39 Ave"

[[trip]]
date = 2024-12-24T00:00:00-08:00
agency = "TransLink"
type = "Bus"
route = "017"
departure = "Oak St @ W 33 Ave"
arrival = "Marine Drive Station"

[[trip]]
date = 2024-12-24T00:00:00-08:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Marine Drive Station"
arrival = "Aberdeen Station"
fare = "CA$3.20"
notes = "Concession fare"

[[trip]]
date = 2024-12-24T00:00:00-08:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Aberdeen Station"
arrival = "Oakridge–41st Ave Station"
fare = "CA$3.20"
notes = "Concession fare"

[[trip]]
dateStr = "Early 2025"
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Oakridge–41st Ave Station"
arrival = "Bridgeport Station"
fare = "CA$3.20"
notes = "Concession fare"


[[trip]]
dateStr = "Early 2025"
agency = "TransLink"
type = "Bus"
route = "620"
departure = "Bridgeport Station"
arrival = "Tsawwassen Ferry Terminal"

[[trip]]
dateStr = "Early 2025"
agency = "BC Ferries"
type = "Ferry"
route = "Coastal Celebration"
departure = "Tsawwassen Ferry Terminal"
arrival = "Swartz Bay Terminal"
fare = "CA$15.00"

[[trip]]
dateStr = "Early 2025"
agency = "BC Ferries"
type = "Ferry"
route = "Spirit of British Columbia"
departure = "Swartz Bay Terminal"
arrival = "Tsawwassen Ferry Terminal"
fare = "CA$15.00"

[[trip]]
dateStr = "Early 2025"
agency = "TransLink"
type = "Bus"
route = "620"
departure = "Tsawwassen Ferry Terminal"
arrival = "Bridgeport Station"
fare = "CA$2.15"
notes = "Concession fare"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 865"
departure = "YVR (CYVR)"
arrival = "HKG (VHHH)"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 316"
departure = "HKG (VHHH)"
arrival = "PVG (ZSPD)"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 381"
departure = "PVG (ZSPD)"
arrival = "HKG (VHHH)"

[[trip]]
dateStr = "Mid 2025"
agency = "Cathay Pacific"
type = "Plane"
route = "CX 888"
departure = "HKG (VHHH)"
arrival = "YVR (CYVR)"

[[trip]]
date = 2025-08-16T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 RapidBus"
departure = "W 41 Ave @ Granville St"
arrival = "W 16 Ave @ Wesbrook Mall"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-16T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 RapidBus"
departure = "W 16 Ave @ Wesbrook Mall"
arrival = "W 41 Ave @ Granville St"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-17T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "025"
departure = "W King Edward Ave @ Granville St"
arrival = "W 16 Ave @ Wallace St"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-17T00:00:00-07:00
agency = "TransLink"
type = "Bus"
route = "025"
departure = "W 16 Ave @ Camosun St"
arrival = "Wesbrook Mall @ 2100 Block"
fare = "CA$2.25"
notes = "Concession fare"

[[trip]]
date = 2025-08-17T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 RapidBus"
departure = "UBC Exchange"
arrival = "W 41 Ave @ Granville St"

[[trip]]
date = 2025-08-28T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Commercial–Broadway station"
arrival = "Metrotown Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-28T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Metrotown Station"
arrival = "Joyce–Collingwood Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-28T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 RapidBus"
departure = "Joyce Station"
arrival = "W 41 Ave @ Granville St"

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "RapidBus"
route = "R4 RapidBus"
departure = "W 41 Ave @ Granville St"
arrival = "Joyce Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Joyce–Collingwood Station"
arrival = "Metrotown Station"
fare = 0.00

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Expo Line"
departure = "Metrotown Station"
arrival = "Waterfront Station"
fare = "CA$3.30"
notes = "Concession fare"

[[trip]]
date = 2025-08-30T00:00:00-07:00
agency = "TransLink"
type = "SkyTrain"
route = "Canada Line"
departure = "Waterfront Station"
arrival = "Oakridge–41st Ave Station"
fare = 0.00
